version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: animaldb-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: animaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - animal_network

volumes:
  postgres_data:

networks:
  animal_network:
    driver: bridge